flask/app/__init__.py
from flask import Flask, make_response, jsonify
from .routes import main
from .user import User
from .chat import chat
from .myinfo import info
from .board import board
# from events import ChatNamepsace
from flask_login import LoginManager, current_user
from datetime import timedelta
from flask_cors import CORS
# from flask_socketio import SocketIO, emit
# import eventlet
# from eventlet import wsgi

login_manager = LoginManager()
# socketio = SocketIO(engineio_logger=True, async_mode='eventlet')


def create_app():

    app = Flask(__name__, static_url_path='/static')
    CORS(app)
    # 임의의 값 실제 배포할때는 랜덤 값 주도록 바꾸기 (개발 때만 고정)
    app.secret_key = "sdfieegrnqgono"
    # 5분 간 세션 유지
    # app.config['PERMANENT_SESSION_LIFETIME'] = timedelta(minutes = 10)

    app.register_blueprint(main)
    app.register_blueprint(chat)
    app.register_blueprint(info)
    app.register_blueprint(board)
    login_manager.init_app(app)  # app 에 login_manager연결
    login_manager.session_protection = "strong"  # session 정보를 복잡하게 만듦

#    socketio.init_app(app)
#    socketio.on_namespace(ChatNamepsace('/allchat'))

    # 콜백, 세션에 저장된 사용자 ID에 사용자 개체를 다시 로드

    @login_manager.user_loader
    def load_user(id):
        return User.get(id)

    @login_manager.unauthorized_handler
    def unauthorized():
        # 로그인되어 있지 않은 사용자일 경우 401 에러 발생
        return make_response(jsonify(sussess=False), 401)

    return app

app = create_app()

flask/app/routes.py
from flask import Flask, session, render_template, request, jsonify, make_response, Blueprint, redirect, url_for, flash
from flask_login import login_user, logout_user, current_user
from .user import User
from flask import Flask
import hashlib
main = Blueprint('main', __name__, url_prefix='/')


@main.route('/')
def home():
    # runserver의 user_loader가 호출됨 flask login이 http request에서 id를 자동으로 넣어줌
    if current_user.is_authenticated:
        return render_template('home.html', login=True)
    else:
        return render_template('home.html')


@main.route('/allchat')
def allchat():
    # runserver의 user_loader가 호출됨 flask login이 http request에서 id를 자동으로 넣어줌
#    if current_user.is_authenticated:
#        session['room'] = 1
#        print("성공")
#        return render_template('allchat.html', room=1, name=current_user.get_user_id())
#    else:
        return redirect(url_for('main.home'))


@main.route('/join', methods=['GET', 'POST'])
def join():
    if request.method == 'POST':
        user_id = request.form['userid']
        name = request.form['name']
        password = request.form['password']
        gender = "남" if request.form['gender'] == 'Male' else "여"
        hashed_password = hashlib.sha256(password.encode('utf-8')).hexdigest()

        SUCCESS = User.join(
            user_id=user_id, password=hashed_password, name=name, gender=gender)
        # 가입 실패
        if not SUCCESS:
            # 경고문 띄우기
            flash("signup failed")
            return render_template('join.html')
        # 가입 성공
        else:
            return redirect(url_for('main.home'))
    else:
        return render_template('join.html')


@main.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        user_id = request.form['userid']
        password = request.form['password']
        hashed_password = hashlib.sha256(password.encode('utf-8')).hexdigest()

        user = User.user_check(user_id, hashed_password)
        # 아이디나 비밀번호가 틀린 경우
        if not user:
            # 경고문 띄우기
            flash("login failed")
            return render_template('login.html')
        else:
            login_user(user)
            return redirect(url_for('main.home'))
    else:
        if current_user.is_authenticated:
            return redirect(url_for('main.home'))
        else:
            return render_template('login.html')


# GET 메소드는 임시로 logout 버튼이 없어서 만들어 놓은것 
@main.route('/logout', methods=['GET'])
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@main.route('/check', methods=['POST'])
def check():
    if request.method == 'POST':
        tdata = request.get_json()
        # 데이터 db넣고 처리한후 ai 응답 담기
        checkID = tdata['id']
        SUCCESS = User.check(checkID)
        if SUCCESS:
            check = {"Check": True}
            return jsonify(result="success", result2=check)
        else:
            check = {"Check": False}
            return jsonify(result="success", result2=check)

flask/app/templates/board.html
<!DOCTYPE html>
<html lang="ko" style="height: 100%;">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/blog-custom.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-latest.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <title>과외 게시판</title>
  </head>
  <body class="bg-dark" style="height: 100%;">

    {% include 'navbar.html' %}

    <div class = "container mt-3">
      <h1 class="mb-5 text-secondary">과외 게시판</h1>
      <table class="table table-dark">
        <thead>
          <tr class="table-active">
            <th>번호</th>
            <th>지역 (구군)</th>
            <th>제목</th>
            <th>작성자</th>
            <th>작성일</th>
            <th>조회수</th>
          </tr> 
        </thead>
        <tbody>
        {% for post in posts %}
          <tr>
            <!-- 0 : 게시글 번호, 3: 제목, 2: 아이디, 5 : 작성자 9: 날짜/시간, 8 : 조회수-->
            <td>{{ post[0] }}</td>
            <td>{{ post[6]}} ({{post[7]}})</td>
            <td><a href="{{ url_for('board.post', index=post[0])}}" ><strong>{{ post[3] }}</strong> <span style="color: #FFA500;">({{ post[10]|string }})</span></a></td>
            <td><strong>{{post[5]}}</strong>({{post[2]}})</td>
            <td>{{ post[9].strftime('%Y-%m-%d') }}</td>
            <td>{{ post[8] }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
      <div class="form-group mt-3 d-flex justify-content-between">
        <a href="{{ url_for('board.main')}}" class="btn btn-secondary">전체 글</a>
        <a href="{{ url_for('board.write')}}" class="btn btn-primary">글쓰기</a>
      </div>
      <div class="d-flex justify-content-center" >
        {{ pagination.links }}
      </div>
      <form action="{{ url_for('board.main')}}" method="GET" class="mb-3" onsubmit="return handleSubmit();">
        <div class="row d-flex justify-content-center">
          <div class="col-lg-2 col-md-2 col-sm-2">
            <select class="form-select me-2" name="category" onchange="handleChange(this)">
              <option value="title">제목</option>
              <option value="name">작성자</option>
              <option value="userid">아이디</option>
              <option value="location">지역+구군</option>
            </select>
          </div>
          <div class="col-lg-6 col-md-6 col-sm-6" id="searchInputContainer">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="검색어를 입력하세요" name="query" id="query">
              <button type="submit" class="btn btn-primary col-sm-2">검색</button>
            </div>
          </div>
        </div>
      </form>
      <script src="../static/js/board.js"></script>
  </body>
</html>

flask/app/templates/chat.html
<!doctype html>
<html lang="ko" style="height: 100%;">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="../static/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
    <script src="https://cdn.WebRTC-Experiment.com/RecordRTC.js";></script>
    <title id="subject">{{subject}}</title>
</head>

<body class="bg-dark" style="height: 100%;">


    {% include 'navbar.html' %}


    <section id="communication" class="container-fluid mt-5 w-100 h-75" style="overflow:auto;">


    <div class="row ms-4">
        <div class="col-12">
        <div class="btn btn-light btn-lg rounded-5 col-3 col-xl-2 text-start disabled">
        <h5 class="text-dark">Ask me question in Text or Voice!</h5>
        </div>
        </div>
    </div>

    </section>


    </div>
    <div class="row" >
        <audio controls class="ms-3 col-9" id="audioe" style="position: fixed; bottom: 70px; display:none"></audio>
    </div>


    <footer class="container-fluid" style="position: fixed; bottom: 0px; height: 60px;">
    <div class="row" >
        <div class="col-9">
        <input type="text" id="question" class="form-control" value =""/>
        </div>
        <div class="col-2">
        <input type = "button" id="text-send" class="form-control" onclick="test_send()" style="display:block;" value="Send">
        <div class="btn btn-light" id="audio_send" onclick="audio_send()" style="display:none;"><i class="bi bi-arrow-up-short"></i></div>
        </div>
        <div class="col-1">
        <div class="btn btn-light " id="start-recording" style="display:block;"><i class="bi bi-mic"></i></div>
        <div class="btn btn-light " id="stop-recording" style="display:none;"><i class="bi bi-pause-circle"></i></div>
        <div class="btn btn-light " id="trash-recording" style="display:none;"><i class="bi bi-trash-fill"></i></div>
        
        <!--
            <i class="bi bi-caret-right-fill">
            <i class="bi bi-pause-circle"></i>
        </i>-->

    </div>
    </div>


</footer>




    <script src="../static/js/chat.js"></script>



</body>
</html>

flask/app/templates/edit.html
<!DOCTYPE html>
<html lang="ko" style="height: 100%;">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>게시글 편집</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/blog-custom.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.20/summernote-bs5.min.css" integrity="sha512-ngQ4IGzHQ3s/Hh8kMyG4FC74wzitukRMIcTOoKT3EyzFZCILOPF0twiXOQn75eDINUfKBYmzYn2AA8DkAk8veQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>
  <body class="bg-dark" style="height: 100%;">
    {% include 'navbar.html' %}

    <main role="main" class="container mt-3">
      <h1 class="text-secondary mb-4">과외 게시글 편집</h1>
      <form name="form" method="POST" action="{{ url_for('board.update', index=index) }}" onsubmit="return handleSubmit();">
          <div class="form-group">
              <label for="title">제목</label>
              <input type="text" id="title" name="title" class="form-control" placeholder="제목을 입력하세요" value="{{ title }}">
          </div>
          <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="citySelect">지역</label>
                    <select name="city" class="form-select" id="citySelect" onchange="loadDistricts()">
                        <option value="">지역을 선택하세요</option>
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="districtSelect">구군</label>
                    <select name="district" class="form-select" id="districtSelect">
                        <option value="">구군을 선택하세요</option>
                    </select>
                </div>
            </div>  
        </div>
          <div class="form-group">
              <label for="content">내용</label>
              <textarea id="summernote" name="content" class="form-control">{{ content }}</textarea>
          </div>
          <div class="form-group mt-3 d-flex justify-content-end">
            <button class="btn btn-success" type="submit">수정완료</button>
          </div>
      </form>
    </main>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.20/summernote-bs5.min.js" integrity="sha512-6F1RVfnxCprKJmfulcxxym1Dar5FsT/V2jiEUvABiaEiFWoQ8yHvqRM/Slf0qJKiwin6IDQucjXuolCfCKnaJQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="/static/js/edit.js"></script>
  </body>
</html>

flask/app/templates/home.html
{% with messages = get_flashed_messages() %}
    {% if messages %}
        <script>
            alert("{{messages[-1]}}")
        </script>
    {% endif %}
{% endwith %}

<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <title>영어 회화</title>
</head>

<body class="bg-dark">

    {% include 'navbar.html' %}

    <header>
        <img class="img-fluid"src="/static/images/header-img.jpg" alt="밤하늘">
    </header>


    <div class="row mt-5 ms-4 border-start">
        <div class="col-7">
            <h1 class="text-white fw-bold">What kind of conversation do you want?</h1>
        </div>
    </div>


    <section class="container overflow-hidden">
    <div class="row">
    <div class="col-12 text-center">
    <span>
        <a href="{{ url_for('chat.text', subject='life')}}" class="btn btn-outline-light col-2 col-xl-3 btn-lg rounded-5 m-5 text-start">
        <h5 class="text-white">Life</h5>
        <h6 class="text-opacity-75 text-secondary"> daily chatting  </h6>
        </a>
    </span>
    <span>
        <a href="{{ url_for('chat.text', subject='business') }}" class="btn btn-outline-light col-3 btn-lg rounded-5 m-5 text-start">
        <h5 class="text-white">Business</h5>
        <h6 class="text-opacity-75 text-secondary"> business conversation </h6>
        </a>
    </span>
    <span>
        <a href="{{ url_for('chat.text', subject='hospital') }}" class="btn btn-outline-light col-2 col-xl-3 btn-lg rounded-5 m-5 text-start">
        <h5 class="text-white">Hospital</h5>
        <h6 class="text-opacity-75 text-secondary"> Hospital chat </h6>
        </a>
    </span>
    </div>
    </div>

    </section>

    <saction class="container">
    <div class="row mt-5 ms-4 border-start">
        <div class="col-7">
            <h1 class="text-white fw-bold">Let's conversate AI</h1>
        </div>
    </div>

    <div class="row mt-5 ms-4">
        <div class="col-12">
            <div class="btn btn-light btn-lg rounded-5 col-5 col-xl-4 text-start disabled">
                <h5 class="text-dark">Hello. Please tell me your health condition.</h5>
            </div>
        </div>
    </div>

    <div class="row mt-3 me-3">
        <div class="col-12">
            <div class="btn btn-light btn-lg rounded-5 col-5 col-xl-4 text-start disabled" style="float:right;">
                <h5 class="text-dark">I have a slight headache and a sore throat. I don't have a fever, but I have a runny nose.</h5>
            </div>
        </div>
    </div>

    <div class="row mt-3 ms-4">
        <div class="col-12">
            <div class="btn btn-light btn-lg rounded-5 col-5 col-xl-4 text-start disabled">
                <h5 class="text-dark">The symptom you mentioned is considered a cold. Take antihistamines and painkillers.</h5>
            </div>
        </div>
    </div>

    <div class="row mt-3 me-3 justify-content-end">
        <div class="col-12  justify-content-end">
            <div class="btn btn-light btn-lg rounded-5 col-5 col-xl-4 text-start disabled" style="float:right;">
                <h5 class="text-dark">Is it okay to take Tylenol?</h5>
            </div>
        </div>
    </div>

    <div class="row mt-3 ms-4 me-5">
        <div class="col-12">
            <div class="btn btn-light btn-lg rounded-5  col-1 col-xl-1 text-start disabled">
                <h5 class="text-dark">. . </h5>
            </div>
        </div>
    </div>

    <div class="row mt-5 ms-4 text-center">
        <h1 class="text-white fw-bold">Contributor</h1>
    </div>

        <div class="container row my-5" style="float: none; margin:0 auto;">
            <div class="col-sm-6 col-lg-3">
                <div class="card bg-secondary opacity-75">
                    <img src="/static/images/header-img.jpg" class="img-fluid p-4 rounded-circle" style="height: 300px; width: 300px;" >
                    <div class="card-body">
                        <h2 class="card-title fs-6 fw-bold">고은우</h2>
                        <p class="card-text">Data Collection, Data Preprocessing, Natural Language rocessing</p>
                        <a href="https://github.com/KNU-bigdata6/bigdata6" class="btn btn-dark rounded-pill"><i class="bi bi-github"></i></a>
                    </div>
                </div>
            </div>

            <div class="col-sm-6 col-lg-3">
                <div class="card bg-secondary opacity-75">
                    <img src="/static/images/header-img.jpg" class="img-fluid p-4 rounded-circle" style="height: 300px; width: 300px;" >
                    <div class="card-body">
                        <h2 class="card-title fs-6 fw-bold">정영진</h2>
                        <p class="card-text">Web Server, database Development, Data Crawling</p>
                        <a href="https://github.com/KNU-bigdata6/bigdata6" class="btn btn-dark rounded-pill"><i class="bi bi-github"></i></a>
                    </div>
                </div>
            </div>

            <div class="col-sm-6 col-lg-3">
                <div class="card bg-secondary opacity-75">
                    <img src="/static/images/header-img.jpg" class="img-fluid p-4 rounded-circle" style="height: 300px; width: 300px;" >
                    <div class="card-body">
                        <h2 class="card-title fs-6 fw-bold">박정용</h2>
                        <p class="card-text">Web Server, Database Development, Data Crawling</p>
                        <a href="https://github.com/KNU-bigdata6/bigdata6" class="btn btn-dark rounded-pill"><i class="bi bi-github"></i></a>
                    </div>
                </div>
            </div>

            <div class="col-sm-6 col-lg-3">
                <div class="card bg-secondary opacity-75">
                    <img src="/static/images/header-img.jpg" class="img-fluid p-4 rounded-circle" style="height: 300px; width: 300px;" >
                    <div class="card-body">
                        <h2 class="card-title fs-6 fw-bold">김혜수</h2>
                        <p class="card-text">Business Design, PPT, Web UI Design</p>
                        <a href="https://github.com/KNU-bigdata6/bigdata6" class="btn btn-dark rounded-pill"><i class="bi bi-github"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    </section>

    <footer class="container-fluid border-top border-secondary mt-5" style="bottom: 0px; height: 200px;">
        <p class="text-secondary mt-2 ms-2"> KNU bigdata6</p>
    </footer>




</body>
</html>

flask/app/templates/navbar.html
<nav class="navbar navbar-dark  border-bottom border-secondary">
    <div class="container-fluid">
        <a class="navbar-brand text-secondary" href="{{ url_for('main.home') }}">MyAIFriend</a>
        <button class="navbar-toggler border-secondary " type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">
                {% if login %}
                <li class="nav-item row text-center">
                    <div class="nav-link col-4 border-bottom border-secondary text-light">Account</div>
                    <div class="nav-link col-4 border-bottom border-secondary text-light">Conversation Type</div>
                    <div class="nav-link col-4 border-bottom border-secondary text-light">Teacher's Bulletin Board</div>
                </li>
                <li class="nav-item row text-center">
                    <a class="nav-link col-4 " href="{{ url_for('info.myinfo') }}">Myinfo</a>
                    <a class="nav-link col-4 " href="{{ url_for('chat.text', subject ='daily') }}">Life</a>
                    <a class="nav-link col-4"  href="{{ url_for('board.main') }}">Board</a>
                </li>
                <li class="nav-item row text-center">
                    <a class="nav-link col-4" href="{{ url_for('main.logout') }}">Logout</a>
                    <a class="nav-link col-4" href="{{ url_for('chat.text', subject ='business') }}">Business</a>
                    <a class="nav-link col-4"  href="{{ url_for('board.write') }}">Write</a>
                </li>
                <li class="nav-item row text-center">
                    <div class="nav-link col-4"></div>
                    <a class="nav-link col-4 " href="{{ url_for('chat.text', subject ='hospital') }}">hospital</a>
                    <div class="nav-link col-4"></div>
                </li>
                {% else %}
                <li class="nav-item align-self-center">
                    <a class="nav-link" href="{{ url_for('main.join') }}">Sign up</a>
                </li>
                <li class="nav-item align-self-center">
                    <a class="nav-link" href="{{ url_for('main.login') }}">Sign in</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

flask/app/templates/write.html
<!DOCTYPE html>
<html lang="ko" style="height: 100%;">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>게시글 등록</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/blog-custom.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.20/summernote-bs5.min.css" integrity="sha512-ngQ4IGzHQ3s/Hh8kMyG4FC74wzitukRMIcTOoKT3EyzFZCILOPF0twiXOQn75eDINUfKBYmzYn2AA8DkAk8veQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>
  <body class="bg-dark" style="height: 100%;">
    <nav class="navbar navbar-dark  border-bottom border-secondary">
      <div class="container-fluid">
          <a class="navbar-brand text-secondary" href="{{ url_for('main.home') }}">MyAIFriend</a>
          <button class="navbar-toggler border-secondary " type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#navbarSupportedContent"
                  aria-controls="navbarSupportedContent"
                  aria-expanded="false"
                  aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">
                {% if login %}
                <li class="nav-item row text-center">
                    <div class="nav-link col-6 border-bottom border-secondary text-light">Account</div>
                    <div class="nav-link col-6 border-bottom border-secondary text-light">Teacher's Bulletin Board</div>
                </li>
                <li class="nav-item row text-center">
                    <a class="nav-link col-6 " href="{{ url_for('info.myinfo') }}">Myinfo</a>
                    <a class="nav-link col-6"  href="{{ url_for('board.main') }}">Board</a>
                </li>
                <li class="nav-item row text-center">
                    <a class="nav-link col-6" href="{{ url_for('main.logout') }}">Logout</a>
                    <a class="nav-link col-6"  href="{{ url_for('board.write') }}">Write</a>
                </li>
                {% else %}
                <li class="nav-item align-self-center">
                    <a class="nav-link" href="{{ url_for('main.join') }}">Sign up</a>
                </li>
                <li class="nav-item align-self-center">
                    <a class="nav-link" href="{{ url_for('main.login') }}">Sign in</a>
                </li>
                {% endif %}
            </ul>
        </div>
      </div>
    </nav>

    <main role="main" class="container mt-3">
      <h1 class="text-secondary mb-4">과외 게시글 작성</h1>
      <form name="form" method="POST" action="{{ url_for('board.write') }}" onsubmit="return handleSubmit();">
          <div class="form-group">
              <label for="title">제목</label>
              <input type="text" id="title" name="title" class="form-control" placeholder="제목을 입력하세요">
          </div>
          <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="citySelect">지역</label>
                    <select name="city" class="form-select" id="citySelect" onchange="loadDistricts()">
                        <option value="">지역을 선택하세요</option>
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="districtSelect">구군</label>
                    <select name="district" class="form-select" id="districtSelect">
                        <option value="">구군을 선택하세요</option>
                    </select>
                </div>
            </div>  
        </div>
          <div class="form-group">
              <label for="content">내용</label>
              <textarea id="summernote" name="content" class="form-control"></textarea>
          </div>
          <div class="form-group mt-3 d-flex justify-content-end">
            <button class="btn btn-success" type="submit">글등록</button>
          </div>
      </form>
    </main>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.20/summernote-bs5.min.js" integrity="sha512-6F1RVfnxCprKJmfulcxxym1Dar5FsT/V2jiEUvABiaEiFWoQ8yHvqRM/Slf0qJKiwin6IDQucjXuolCfCKnaJQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="/static/js/write.js"></script>
  </body>
</html>